<a href="https://colab.research.google.com/github/krishnasidhvi/krishna_data690/blob/main/assignment_05/Assignment5_Part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part-4 : Intro to Numpy

In [141]:
import sys
import numpy as np
import warnings

#Basic Numpy Arrays

In [142]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [143]:
a = np.array([1, 2, 3, 4])


In [144]:
b = np.array([0, .5, 1, 1.5, 2])


In [145]:
a[0], a[1]

(1, 2)

In [146]:
a[0:]

array([1, 2, 3, 4])

In [147]:
a[1:3]

array([2, 3])

In [148]:
a[1:-1]


array([2, 3])

In [149]:
a[::2]


array([1, 3])

In [150]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [151]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [152]:
b[[0, 2, -1]]

array([0., 1., 2.])

#Array Types

In [153]:
a

array([1, 2, 3, 4])

In [154]:
a.dtype

dtype('int64')

In [155]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [156]:
b.dtype

dtype('float64')

In [157]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [158]:
np.array([1, 2, 3, 4], dtype=np.int8)


array([1, 2, 3, 4], dtype=int8)

In [159]:
c = np.array(['a', 'b', 'c'])

In [160]:
c.dtype

dtype('<U1')

In [161]:
d = np.array([{'a': 1}, sys])


In [162]:
d.dtype

dtype('O')

#Dimesnsions and shapes

In [163]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [164]:
A.shape

(2, 3)

In [165]:
A.ndim

2

In [166]:
A.size

6

In [167]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [168]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [169]:
B.shape


(2, 2, 3)

In [170]:
B.ndim

3

In [171]:
B.size

12

In [172]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [173]:
C.dtype

dtype('O')

In [174]:
C.dtype

dtype('O')

In [175]:
C.size

2

In [176]:
type(C[0])

list

#Indexing and Slicing of Matrices

In [177]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [178]:
A[1]

array([4, 5, 6])

In [179]:
A[1][0]

4

In [180]:
# A[d1, d2, d3, d4]

In [181]:
A[1, 0]

4

In [182]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [183]:
A[:, :2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [184]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [185]:
A[:2, 2:]

array([[3],
       [6]])

In [186]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [187]:
A[1] = np.array([10, 10, 10])

In [188]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [189]:
A[2] = 99

In [190]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#Summary statistics

In [191]:
a = np.array([1, 2, 3, 4])

In [192]:
a.sum()

10

In [193]:
a.mean()

2.5

In [194]:
a.std()

1.118033988749895

In [195]:
a.var()

1.25

In [196]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [197]:
A.sum()

45

In [198]:
A.mean()

5.0

In [199]:
A.std()

2.581988897471611

In [200]:
A.sum(axis=0)

array([12, 15, 18])

In [201]:
A.sum(axis=1)

array([ 6, 15, 24])

In [202]:
A.mean(axis=0)

array([4., 5., 6.])

In [203]:
A.mean(axis=1)

array([2., 5., 8.])

In [204]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [205]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#Broadcasting and Vectorized operations

In [206]:
a = np.arange(4)

In [207]:
a

array([0, 1, 2, 3])

In [208]:
a + 10

array([10, 11, 12, 13])

In [209]:
a * 10

array([ 0, 10, 20, 30])

In [210]:
a

array([0, 1, 2, 3])

In [211]:
a += 100

In [212]:
a

array([100, 101, 102, 103])

In [213]:
l = [0, 1, 2, 3]

In [214]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [215]:
a = np.arange(4)


In [216]:
a

array([0, 1, 2, 3])

In [217]:
b = np.array([10, 10, 10, 10])

In [218]:
b

array([10, 10, 10, 10])

In [219]:
a + b

array([10, 11, 12, 13])

In [220]:
a * b

array([ 0, 10, 20, 30])

#Boolean arrays

In [221]:
a = np.arange(4)

In [222]:
a

array([0, 1, 2, 3])

In [223]:
a[0], a[-1]


(0, 3)

In [224]:
a[[0, -1]]


array([0, 3])

In [225]:
a[[True, False, False, True]]

array([0, 3])

In [226]:
a

array([0, 1, 2, 3])

In [227]:
a >= 2

array([False, False,  True,  True])

In [228]:
a[a >= 2]

array([2, 3])

In [229]:
a.mean()

1.5

In [230]:
a[a > a.mean()]

array([2, 3])

In [231]:
a[~(a > a.mean())]


array([0, 1])

In [232]:
a[(a == 0) | (a == 1)]


array([0, 1])

In [233]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [234]:
A = np.random.randint(100, size=(3, 3))

In [235]:
A

array([[55, 82,  4],
       [57, 58, 42],
       [86, 60, 35]])

In [236]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([55,  4, 58, 86, 35])

In [237]:
A > 30

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [238]:
A[A > 30]


array([55, 82, 57, 58, 42, 86, 60, 35])

#Linear Algebra

In [239]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [240]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [241]:
A.dot(B)


array([[20, 14],
       [56, 41],
       [92, 68]])

In [242]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [243]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [244]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [245]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#Size of objects in Memory

 ## Int, floats

In [246]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [247]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [248]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [249]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [250]:
np.dtype(float).itemsize

8

# Lists are even larger

In [251]:
# A one-element list
sys.getsizeof([1])

80

In [252]:
# An array of one element in numpy
np.array([1]).nbytes

8

#And performance is also important

In [253]:
l = list(range(100000))

In [254]:
a = np.arange(100000)

In [255]:
%time np.sum(a ** 2)

CPU times: user 519 µs, sys: 0 ns, total: 519 µs
Wall time: 530 µs


333328333350000

In [256]:
%time sum([x ** 2 for x in l])

CPU times: user 48 ms, sys: 491 µs, total: 48.4 ms
Wall time: 55.1 ms


333328333350000

#Useful Numpy functions

##random

In [257]:
np.random.random(size=2)

array([0.49668171, 0.92555514])

In [258]:
np.random.normal(size=2)


array([-0.56346306, -1.51169847])

In [259]:
np.random.rand(2, 4)

array([[0.511674  , 0.83132853, 0.08472404, 0.48224023],
       [0.37480625, 0.42122931, 0.25698626, 0.42833242]])

#arrange

In [260]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [261]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [262]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#reshape

In [263]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [264]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#Linespace

In [265]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [266]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [267]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# zeros, ones, empty

In [268]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [269]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [270]:
np.zeros((3, 3), dtype=np.int)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [271]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [272]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [273]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [274]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

#Identity and eye

In [275]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [276]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [277]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [278]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [279]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [280]:
"Hello World"[6]


'W'